version: '3'

services:

  # Database
  db:
    image: mysql:latest
    volumes:
      - db_vol:/var/lib/mysql
    restart: always
    env_file:
      - db.env
    
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    env_file:
      - pma.env

    networks:
      - wpsite

  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: 
      - wp_vol:/var/www/html
    env_file:
      - wp.env

    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_vol:
  wp_vol: